version: '3.9'
services:
  postgres:
    image: postgres:13.5 #Specifies the Docker image for the PostgreSQL database
    container_name: ecommerce_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #pgadmin:
  #  image: dpage/pgadmin4
  #  container_name: ecommerce_pgadmin
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: admin@local
  #    PGADMIN_DEFAULT_PASSWORD: admin
  #  ports:
  #    - "5050:80"
  #  depends_on:
  #    - postgres

volumes:
  postgres_data:
