services:
  - type: web
    name: alnakheel-api
    env: node
    plan: free
    region: oregon

    buildCommand: |
      npm ci
      npx prisma generate
      npx prisma migrate deploy
      npm run build

    startCommand: npm run start

    postDeployCommand: npm run prisma:seed

    envVars:
      - key: DATABASE_URL
        fromService:
          name: alnakheel
          type: postgres
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: binary
    # Notice: PORT is not hardcoded

    healthCheckPath: /api/health
    autoDeploy: true
